FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet publish Mediport_Backend/WebApplication1/WebApplication1.WebApi.csproj \
    -c Release \
    -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /out .

ENTRYPOINT ["dotnet", "WebApplication1.WebApi.dll"]